version: '3'

services:
  rust-stats:
   image: whitlocktech/rust-stats:1.1.3
   container_name: Rust-Stats
   ports:
     - 5500:5500
   volumes:
     - ./log:/log
   environment:
     - PORT=5500
     - HOST=192.168.0.133
     - USER=playerranks
     - PASSWORD=test
     - DB=playerranks
     - STEAM_API_KEY=<STEAM_API_KEY>
   restart: unless-stopped